### ISSUE TITLE
When the task is added, the scroll bar does not change beyond the maximum width

### ISSUE THREAD

**Issue by qinouz** [DHTMLX/vue-gantt-demo#2]

**Comment by AlexKlimenkov** [comment]
Hi,
this is expected behavior,
the visible range is defined either by start_date/end_date configs https://docs.dhtmlx.com/gantt/api__gantt_start_date_config.html - in that case, it doesn't depend on loaded tasks, tasks outside specified range are not displayed,
or it's defined by tasks loaded into gantt - in that case scale range is recalculated after gantt.load/gantt.parse or after complete repaint via gantt.render
If you want the time scale to extend automatically after adding/editing tasks, you can try this config https://docs.dhtmlx.com/gantt/api__gantt_fit_tasks_config.html
